---
name: xcop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: g4s8/xcop-action@master
